### ISSUE TITLE
Improved Compatibility with Kerbalism

### ISSUE THREAD

**Issue by CaesarVincens** [Angel-125/MOLE#11]
Kerbalism has had several changes to its default profile and how it handles science. It now includes water by default as a life support resource as well as adding a habitat feature to kerbal holding pods. Habitats can have one or two of several life support features such as pressure control or CO2 scrubbing. Also Kerbalism installs its own science and comm system which replaces the stock system.

Mostly, this affects resources retained or held by the WBI configurable system (pods don't keep all resources from Kerbalism e.g.) and the MOLE/Bigby's bonus science which cannot be transmitted by the Kerbalism comm system.

Additionally, some of the current Kerbalism MM patch changes are outdated, specifically, the 'Entertainment' modules which has replaced by 'Comfort' modules.

If you would like any examples of new changes or some of my patches, I am happy to help.

**Comment by Angel-125** [comment]
Er, do you have a pull request with the changes?

**Comment by CaesarVincens** [comment]
I will write one up for you soon.

**Comment by CaesarVincens** [comment]
I should be able to write up some MM patches to set how many and which life support systems are allowed in given parts if you like as well or write up an example for you to work with.

**Comment by CaesarVincens** [comment]
I've been looking at the Kerbalism default profile and I've found that 31.45 food, 12.1 water, and 2978.64 oxygen will sustain one kerbal for 5 days on the default profile. Hope that helps for balancing purposes.
