### ISSUE TITLE
Botany Lab

### ISSUE THREAD

**Issue by DrFish6t9** [Angel-125/MOLE#15]
Hi, Just a question really.

Had a "station" up for the month with the MOLE Botany lab which completed 1 cycle and grew (if I remember correctly) 90 saplings (or something of that ilk), my question is what happens to them as they vanished and I do not remember receiving any science from them.
Probably missing something to make them into something else/something useful.
Thanks for your cool mod, its not KSP for me without them.

**Comment by Angel-125** [comment]
The Botany Lab's experiment grows Plants, and they're consumed by the MOLE Lab's science experiment.
