### ISSUE TITLE
Impossible science contracts

### ISSUE THREAD

**Issue by Svish** [Angel-125/MOLE#18]
Took a science contract that seemed fairly alright. Then while looking over the equipment I would need, it seems I would need the MOLE for some of them, and with MOLE experiments listed under `Situation: Flying low`...

Wouldn't this contract be kind of impossible to do, as they require LabTime? Pretty sure I can't make anything to stay flying in one biome for long enough to complete those experiments... 😨

![capture](https://user-images.githubusercontent.com/142162/27451034-12726678-578e-11e7-9051-9b88f9cf2c31.PNG)

**Comment by Angel-125** [comment]
You actually could do this contract with Heisenberg and AirPark :)

**Comment by Svish** [comment]
![hmmm](https://media.giphy.com/media/kaq6GnxDlJaBq/giphy.gif)

😛
