### ISSUE TITLE
EPL Workshop Missing from parts

### ISSUE THREAD

**Issue by MrKiel** [Angel-125/MOLE#27]
Hi, 

I've been trying to figure out why the Extraplanetary Launchpads workshop wasn't working on parts in this mod. 

It's because the module in the MM patches for EL in both MOLE and Pathfinder use the incorrect module name - "ExWorkshop" should be "ELWorkshop". 

I changed the name in the MM Patches and everything's good.

**Comment by Angel-125** [comment]
Fixed in current release, thanks! :)
