### ISSUE TITLE
LDEF Botany wedge resource

### ISSUE THREAD

**Issue by JadeOfMaar** [Angel-125/MOLE#29]
Since your move from CRP to Classic, you haven't update the file at [LDEF Botany Module](https://github.com/Angel-125/MOLE/blob/master/GameData/WildBlueIndustries/MOLE/LDEF/LDEFBotanyModule.cfg) to call for Compost and to hold an amount of it over Fertilizer. This leads to harmless nulls and the part being useless.

**Comment by Angel-125** [comment]
Thanks, I'll correct that
