### ISSUE TITLE
No Comms

### ISSUE THREAD

**Issue by DrFish6t9** [Angel-125/MOLE#7]
Hi,

I love the MOLE and it is what I use to go into space, the back seat is brilliant.
But I put a couple of labs into orbit and did some research but when it came to transmit I got the error of no comms.
So I landed the labs and did some research on the landing pad with every comms device I have all switched on and targeting mission control (both tried with the launch clamps on and off) and once again no comms, but the strange thing is that I could transmit science from experiments (analyse telemetry from the titan core).
I have v0.5.0, remote tech, antennas, dmagic orbital science, for science cont, orbital science mods (to name a few).
Also when creating the craft if I choose C&C it says no C&C controls available.
Do you know if its a problem of that it is not compatible with certain mods as I will dump those others.

**Comment by Angel-125** [comment]
Interesting! When I get home I'll do some research on this and find out what's going on. Which lab configuration did you use, the basic research lab or the MPL?
Thanks for the feedback. :)

**Comment by DrFish6t9** [comment]
The set-up was 2 mole labs (I've only unlocked 1 and haven't unlocked the MPL as that is next on the nodes) sandwiched between a titan instrument thingy. It had a couple of octocores with food and the like for TAC Life support (didn't want my Kerbols to snuff it in space). The rocket was a set of titan parts.
Is there a certain antenna you need to use to transmit or need some kind of additional component as that was practically all my lab was (batteries and solar as well).

**Comment by Angel-125** [comment]
No special antennas required, it uses the stock ones. I'll see what's going on, sounds like a bug of some sort.

**Comment by DrFish6t9** [comment]
Another little thing has surfaced, I cannot seem to get a Kerbol through the Mk1 docking port (the description says they can, but connected living space does not say they can pass through).
I tried the simple thing of 2 Brumby tip to tip, able to move through on their own, but put a docking port on the top of each (flange to flange) and transfer crew does not work (hatches are open).

**Comment by Angel-125** [comment]
Ok, sounds like another issue with CLS. There is a MM_CLS file in the MOLE folder. If you take the part name of the Mk1 docking port and add it to the MM_CLS patch, it should work. I'll have that officially patched next update. :)

**Comment by DrFish6t9** [comment]
I'll try to make that fix, is there anything from the antenna problem?
I will have to put my space station back into orbit (when I get the tech back) as I made a little boobo.
I was clearing the old junk (spent boosters and the like) from orbit in the tracking station but I really wasn't paying attention and deleted the space station with all my kerbins in it, no funds left to replace them so back to the start!

**Comment by Angel-125** [comment]
I've just verified that the MOLE lab is working properly to transmit data. I made sure to use a stock antenna and generated science. I'm about to release the KSP 1.1 version of MOLE, please be sure to install everything from GitHub. I don't trust CKAN to get this update right.

**Comment by DrFish6t9** [comment]
It must have been another mod that caused the problem to it as I tried every comms device I had unlocked.
Game does look better now its updated (and 64bit loaded!!!!!)
